module.exports = [
    'gotta pump these numbers up',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'my dudes',
    'getting a little cramped my dudes',
    'getting a little cramped my dudes',
    'getting a little cramped my dudes',
    'getting a little cramped my dudes',
    'getting a little cramped my dudes',
    `we've hit maximum bants`
  ];
  